"""Change in Transaction Table

Revision ID: 24d6ef6541d7
Revises: 7b3eb846d1d3
Create Date: 2025-08-10 01:25:22.175790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24d6ef6541d7'
down_revision: Union[str, Sequence[str], None] = '7b3eb846d1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('to_account',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='to_account::integer')
        batch_op.drop_column('from_account')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='role'),
               nullable=True,
               existing_server_default=sa.text("'USER'::role"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='role'),
               nullable=False,
               existing_server_default=sa.text("'USER'::role"))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_account', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.alter_column('to_account',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
