"""Change in Transaction Table(Add Date)

Revision ID: dd8359da1607
Revises: 24d6ef6541d7
Create Date: 2025-08-10 01:36:14.766805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8359da1607'
down_revision: Union[str, Sequence[str], None] = '24d6ef6541d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        # Add column with a default value for existing records
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        
    # Remove the server_default after adding (optional)
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('date', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
